[package]
name = "tokio_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
chrono = "0.4.38"
lazy_static = "1.4.0"
tokio = { version = "1.37.0", features = ["full"] }

# xcp = { git = "https://github.com/vectorgrp/xcp-lite" }
xcp = { path = "../../" }
xcp_type_description_derive = { path = "../../xcp_type_description_derive/" } 


[profile.dev.package."*"]
debug = false
opt-level = 3

[profile.dev]
panic = 'abort'
debug = true
# lto = true
opt-level = 2


